### ISSUE TITLE
api: please provide an atomic non-updating insert

### ISSUE THREAD

**Issue by lucab** [alexheretic/linked-hash-set#1]
First, thanks for maintaining this crate! I was going through the documentation, and I was quite surprised to see that `insert()` is really an "upsert", i.e. it always updates pre-existing keys altering existing order.
This is a subtle problem for the following usecase I have: when merging ordered entries from multiple collections into a single linked-hash-set, the original relative order must be retained.

What I'd like to have here is some method which atomically check if a key is already present, and insert iff it is missing. Current alternatives I see are, in my order of preference:
 1. duplicate `insert` to `upsert`, then change+document new behavior of `insert`
 1. add a new `insert_missing` method with such conditional behavior. We can bikeshed on the new method name: "insert_only", "conditional_insert", "insert_if_missing" or similar ones
 1. add an `update: bool` parameter to current `insert`

I'm happy to provide code and tests for this, but I'd need a bit of input on the API design side. I didn't check what other language libraries do (Java/C++), but you may want to cross-check first. The final UX experience I'd like to have is (placeholder `insert_only` method name):
```
let mut set = LinkedHashSet::new();
set.insert_only(234);
set.insert_only(123);
set.insert_only(345);
let inserted = set.insert_only(123);

assert_eq!(inserted, false);
assert_eq!(set.into_iter().collect::<Vec<_>>(), vec![234, 123, 345]);
```

**Comment by alexheretic** [comment]
The set behaviour is very much limited to the behaviour of `LinkedHashMap` as this provides all the underlying functionality. While having syntax as close as possible to std `HashSet`.

This is expected behaviour of the map, similar to Java's linked hash map. So since the map implementation doesn't have this the set won't either. 

You can, of course, add your own trait with a method and implement it for `LinkedHashSet` by wrapping the `insert` in a `!contains`. (I'm on my phone at the moment so I hope that makes sense).

You could also raise this as an issue on the linked-hash-map crate, though they seem to have shut down maintenance. Finally, also consider `OrderMap` which should behave this way on inserts iirc.

**Comment by lucab** [comment]
> This is expected behaviour of the map, similar to Java's linked hash map

That's a different context though, as with a map insertion one may keep the same key but update the value. In a set, this case does not exist.

> by wrapping the insert in a !contains

That's what I'm currently doing, but this is really a library primitive, not something to bolt-on everywhere.

> Finally, also consider OrderMap which should behave this way on inserts iirc.

~~I quickly skimmed through that and it seems to have the same behavior~~ (I need both behaviors in different cases anyway actually). Thanks for the suggestion though, I was not aware of that crate!

I'm now puzzled about the relationship between this crate and "ordermap", and where to go from here. Should I try to manage my way through `LinkedHashMap` (unlikely due to death notice) or move on to `OrderSet` (isn't this just library duplication)?

Thanks for your quick answer by the way!

**Comment by alexheretic** [comment]
`OrderSet|Map` is backed by an array so acts differently when you remove elements, like `Vec::swap_remove`. On the other hand a linked list can do mid list removals in constant time without affecting the order of the remaining elements.

I think I'll add a note comparing the lib to the readme, if you don't care about the removal effects OrderMap is the better option.

I am coming round to your idea though, how about adding `insert_if_absent` and we improve the docs to `insert` to mention the effects on ordering?

**Comment by lucab** [comment]
Thanks for the explanation. A short recap of the differences in the readme could help casual readers like me, yes. But I wasn't aware of the other crate at all, so my fault for not checking better.

I had a quick look around to see what other languages and libraries do, and I've found a note on Java `LinkedHashSet::add()` which says "insertion order is not affected if an element is re-inserted into the set": https://docs.oracle.com/javase/7/docs/api/java/util/LinkedHashSet.html

Moreover, you were right and I was wrong: `OrderSet::insert()` doesn't affect the order on re-insertion.

Given that, I would just align this to the other two for simplicity, and have an `insert`/`upsert` pair. This would help lowering the cognitive load and avoid the surprise factor. Otherwise yes, what you suggested would also be in principle fine as a fallback, but it would a one-off peculiarity of this library.

**Comment by alexheretic** [comment]
It's a fair point about Java `LinkedHashSet`. 

I've made #3 with where I'm currently leaning.

Tbf while I don't like 'upsert' as much, I wouldn't mind `insert` & `insert_refresh` (as upstream uses this terminology). However, right now I think its more _'obvious'_ that `set::insert` is exactly the same as `map::insert` as we stress this is simply a set implementation using `LinkedHashMap`.

**Comment by lucab** [comment]
Just for terminology reference, `upsert` comes from DB world: https://wiki.postgresql.org/wiki/UPSERT

It describes a `INSERT ... ON CONFLICT UPDATE` semantic, which is the current behavior of `insert`. I also like the `_refresh` proposal.

**Comment by alexheretic** [comment]
Yep that's where I'm used to the term. I explained why I'm not sure it's as good a fit for a set/map in #3.

So I'm still leaning toward the `insert_if_absent` solution because I like the set/map insert being the same & don't really want to change insert behaviour.
