### ISSUE TITLE
Make iterators double-ended

### ISSUE THREAD

**Issue by remexre** [alexheretic/linked-hash-set#4]
It's useful for me to have a reverse iterator through the `LinkedHashSet`.

**Comment by alexheretic** [comment]
Thanks, I've added `DoubleEndedIterator` implementations for `.iter()` & `.into_iter()` with c270eba. Is that sufficient for what you need?

**Comment by alexheretic** [comment]
Available in `0.1.3`

**Comment by remexre** [comment]
Sorry for taking so long to get back to you on this; it works great.
