### ISSUE TITLE
Highlight insert_if_absent

### ISSUE THREAD

**Issue by dbdr** [alexheretic/linked-hash-set#5]
The example in the Readme uses insert and the assert shows that it changes the order for duplicate inserts. I initially thought that's a problem since it's not the behaviour I need now. It's great that insert_if_absent exists too. I'm suggesting to mention it in the Readme, since insertion order is the key feature of this crate.

**Comment by alexheretic** [comment]
We can add a small comment to the readme example before the duplicate insert.

I think the docs themselves are clear enough for these two methods, would you agree?

**Comment by dbdr** [comment]
Thanks! Yes, I agree the docs are clear.

**Comment by alexheretic** [comment]
I've updated the example, hope it helps the next guy.

**Comment by dbdr** [comment]
Thank you!
