### ISSUE TITLE
How to compare sets taking into account order

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [alexheretic/linked-hash-set#7]
I'd like to compare two ordered sets in a way that takes order into account. Is that possible?

This test passes (i.e. considers the sets equal).

```rust
        #[test]
        fn linked_set_equality() {
            let mut set1 = LinkedHashSet::new();
            assert!(set1.insert(234));
            assert!(set1.insert(123));
            assert!(set1.insert(345));

            let mut set2 = LinkedHashSet::new();
            assert!(set2.insert(123));
            assert!(set2.insert(345));
            assert!(set2.insert(234));

            assert_eq!(set1, set2);
        }
```

**Comment by alexheretic** [comment]
It's correct the the `PartialEq` implementation acts similarly to `HashSet` and disregards order. It's somewhat debatable which behaviour is least surprising. However, [indexmap::IndexSet](https://docs.rs/indexmap/1.6.2/src/indexmap/set.rs.html#860-869) also behaves this way.

If you want a stricter version perhaps defining a function would suffice? E.g. adding this to your test case:
```rust
/// Returns true if the given sets are equal and have identical iteration order.
fn equal_and_same_order(a: &LinkedHashSet<i32>, b: &LinkedHashSet<i32>) -> bool {
    a.len() == b.len() && a.iter().eq(b)
}

assert!(!equal_and_same_order(&set1, &set2));

let mut set3 = LinkedHashSet::new();
assert!(set3.insert(234));
assert!(set3.insert(123));
assert!(set3.insert(345));

assert!(equal_and_same_order(&set1, &set3));
```

There's probably a case for having a `LinkedHashSet` method for this. And perhaps documentation could be improved?

**Comment by andrewdavidmackenzie** [comment]
Thanks for the help. 

I have a PartialEq implementation for the struct holding this so I just plugged in the .iter().eq() code into it (didn't know that would work) and that solves my needs.

Personally, I would have it do a comparison based on order, so that the distinguishing feature of this Set over HashMap (i.e. Order) is extended to the PartialEq implementation. 

If the trait implementation doesn't do that, then a method for it would make sense IMO.

thanks again.
