### ISSUE TITLE
self.back() should not take &mut self

### ISSUE THREAD

**Issue by dchen5022** [alexheretic/linked-hash-set#8]
self.back() takes &mut self but self.front() takes &self. This doesn't look right unless I am missing something.

**Comment by dchen5022** [comment]
Looks like this was mistakenly added in the internal LinkedHashMap but is now fixed:
https://github.com/contain-rs/linked-hash-map/commit/38d9666fae8dfb702cbc8a3c554ca22d10d6ac0f

**Comment by alexheretic** [comment]
Thanks! I'll publish a new version soon with this addressed.

**Comment by dchen5022** [comment]
Thanks so much for the quick response!
